CREATE TABLE "Customer_Credit_Score" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT,
    credit_score BIGINT
);

CREATE TABLE "Customer_Account_Status" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    nationality TEXT,
    email TEXT,
    account_status TEXT,
    id_number TEXT
);

CREATE TABLE "Government_PR_Status" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT,
    pr_status BOOLEAN
);